### ISSUE TITLE
No property for VAT Number on Customer

### ISSUE THREAD

**Issue by TimS-** [kfrancis/chargify-dot-net#11]

**Comment by TimS-** [comment]
This seems to be due to the property not being returned in any API endpoints by Chargify which is odd as it's a propery of the Customer in the UI. Asking support

**Comment by TimS-** [comment]
Turn out the field is only sent back when a customer has a vat_number value set. It's undocumented as far as I can see but I can see it in a raw API request for a customer of mine where the field has a VAT value. Would be great to have this optional field added into the .Net wrapper.

**Comment by janigorse** [comment]
I am also interested in getting vat_number. Could this be included in .net wrapper any time soon?

**Comment by kfrancis** [comment]
Anyone want to fork and add a pull request?

**Comment by TimS-** [comment]
Any joy with this change? It would be a huge help, and while I'm happy to contribute a fix I'm not at all familiar with this library and how to correctly make this change in all the necessary places.

**Comment by TimS-** [comment]
I see there is an open PR for this

**Comment by kfrancis** [comment]
Merged
