### ISSUE TITLE
Referral code functionality not implemented

### ISSUE THREAD

**Issue by TimS-** [kfrancis/chargify-dot-net#13]
The Subscription#create API endpoint now takes an optional ref parameter.

https://docs.chargify.com/referrals
https://docs.chargify.com/api-subscriptions

**Comment by kfrancis** [comment]
I'll take a look.

**Comment by TimS-** [comment]
Any joy with this one? Cheers

**Comment by kfrancis** [comment]
Adding parameters to subscription create is getting to be unweildy. I'm looking at refactoring subscription create to take a single "options" parameter and doing it that way.

**Comment by kfrancis** [comment]
@TimS- The refactor included the "ref" param, but the rest I'm committing right now.

**Comment by kfrancis** [comment]
(Thanks to @jamzi)
