### ISSUE TITLE
TLS Upgrade 12 January 2016

### ISSUE THREAD

**Issue by TimS-** [kfrancis/chargify-dot-net#16]
Chargify are no longer supporting TLS 1.0 and 1.1 from 12 January 2016 (https://docs.chargify.com/tls-upgrade-notice). In my Chargify control panel I saw a notification saying "We’re concerned that your Chargify integration will stop working on Jan 12, 2016. Please see your ​TLS Check page (https://app.chargify.com/tls_check) for more information."

Sure enough that page shows a that the client 'Chargify.NET Client v1.1.5738.19989' is using TLSv1.

I believe a configuration change is necessary to explicitly set the `ChargifyConnect.ProtocolType` to `SecurityProtocolType.Tls12` as this is now the only supported protocol. It could be that this is unnecessary and it will switch automatically? But as I couldn't see it documented on the project here I thought I'd ask just in case come D-Day anyone has any issues.

**Comment by Jabberrwocky** [comment]
Hi TimS,

I am glad I found your post. I kept running into the following error

    {"The underlying connection was closed: An unexpected error occurred on a send."}
    {"Authentication failed because the remote party has closed the transport stream."}

Once I manually set `ChargifyConnect.ProtocolType` to `SecurityProtocolType.Tls12` everything worked as it should

**Comment by kfrancis** [comment]
Yes - so I added that property long ago when I removed the explicit setting of SecurityProtocolType in versions earlier than [Chargify.NET v1.1.5400.37999](http://chargify.codeplex.com/SourceControl/changeset/89147). Everything after 37999 removes the hard-coded value and allows it to be set, which you can set to TLS 1.2 if using .NET 4+ (details about the values on the Chargify documentation).
