### ISSUE TITLE
Can't read payment profiles?

### ISSUE THREAD

**Issue by bevnetcraven** [kfrancis/chargify-dot-net#17]
It seem as though this part of the API is not fully implemented...or am I missing something? 

https://docs.chargify.com/api-payment-profiles

Thanks in advance!

**Comment by rickstricker** [comment]
Dang.  I'm needing this as well.  Unfortunately, Authorize.Net only supports expiration updates through the payments profile interface.

**Comment by kfrancis** [comment]
Hmm - what part explicitly?

**Comment by bevnetcraven** [comment]
@kfrancis I'm looking for these methods: https://docs.chargify.com/api-payment-profiles

Idea being that we'd like to allow existing customers to see existing payment profiles and select from them rather than have to always enter new credit card info.

**Comment by rickstricker** [comment]
...and in my case, this is the only way that Authorize.Net allows the updating of the expiration date. 

See: https://docs.chargify.com/api-subscriptions#update
>> "Note that partial card updates for Authorize.Net are not allowed via this endpoint."

**Comment by kfrancis** [comment]
Hmm - I'll take a look.

**Comment by kfrancis** [comment]
Done, [added](https://github.com/kfrancis/chargify-dot-net/commit/0a3bc04f02b2b5c4dafae67174ac5295e6e94b68) and [released](https://github.com/kfrancis/chargify-dot-net/releases/tag/v1.1.5879.22909). Thanks for the feedback!
