### ISSUE TITLE
No UpdateProduct?

### ISSUE THREAD

**Issue by dbruning** [kfrancis/chargify-dot-net#18]
Hi,

I'm using ChargifyDotNet to check and move configuration changes between sites. Thanks for the excellent work!

I noticed that there is no UpdateProduct method. There is an UpdateCustomer method, and Customers have settable properties - but Products seem to have properties that are get-only.
Is this by design? It seems like the [Chargify API](https://docs.chargify.com/api-products#update) allows product updates, so I'm wondering why ChargifyDotNet doesn't.

**Comment by kfrancis** [comment]
Chargify opened that up eventually. Back when this was first added, you could only update the products through the admin.

Should be fairly easy to add if you wanted to tackle that.

**Comment by dbruning** [comment]
Ah right. I've scratched my immediate itch by hitting the API directly, but would like to come back & help add this in to chargify.net at some stage.

**Comment by kfrancis** [comment]
Released in v1.1.5898.21530
