### ISSUE TITLE
Product: return_url and return_params seem to have been renamed at Chargify

### ISSUE THREAD

**Issue by dbruning** [kfrancis/chargify-dot-net#19]
Per the [Chargify docs](https://docs.chargify.com/api-products), there is no return_url and return_params; there is only update_return_url and update_return_params

(Interestingly, return_params still seems to be included the the product XML from Chargify, but return_url is not).

I've had a go at fixing this, will submit a PR.

**Comment by kfrancis** [comment]
Thanks! I'll get this released, but it has already been merged.
