### ISSUE TITLE
Bug in "UpdateTheSubscriptionCreditCard" method

### ISSUE THREAD

**Issue by bieoe** [kfrancis/chargify-dot-net#2]
In the private method for updating the subscription credit card, the CVV's length is checked if the CVV is required in Chargify. HOWEVER, it is possible to pass in a null value for the CVV if that value should not be updated. Because there is no check to see if the CVV is null, the call to this method throws a null object reference exception. This bug makes it impossible to update just the billing address from the library.

**Comment by kfrancis** [comment]
Currently there's a property of ChargifyConnect `CvvRequired`. Set `CvvRequired` = false for those cases for now.
