### ISSUE TITLE
Medium Trust Host Error Since upgrading to .NET 4+

### ISSUE THREAD

**Issue by OSPete** [kfrancis/chargify-dot-net#25]
In upgrading to the latest version (to fix the bad request issue with customer update) we've been experiencing the following error when trying to run in our hosted environment.

> Inheritance security rules violated while overriding member: 'ChargifyNET.ChargifyException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

Our site is hosted on Rackspace Cloud Sites where they run with [Modified Medium Trust](https://support.rackspace.com/how-to/modified-medium-trust-on-cloud-sites/). 

This seems to have been introduced by the recent update in Chargify.NET to .NET 4+ ([Security Changes](https://msdn.microsoft.com/en-us/library/dd233103(v=VS.100).aspx))

I've researched this problem today and have implemented and tried a few of the suggested fixes for it but I've been unable to fix the issue at this time.

**Comment by kfrancis** [comment]
My only question is if that will mess up serialization. Do you know? If it won't then it can just be commented out.

**Comment by kfrancis** [comment]
Fixed in release `1.1.5935.32008`
