### ISSUE TITLE
NuGet Package has Microsoft.Net.Compilers dependency

### ISSUE THREAD

**Issue by LordJZ** [kfrancis/chargify-dot-net#26]
As far as I see Microsoft.Net.Compilers is used for development only, but here on nuget I see this dependency: 
https://www.nuget.org/packages/chargify/
Microsoft.Net.Compilers (>= 1.1.1)

**Comment by kfrancis** [comment]
Is it?

**Comment by LordJZ** [comment]
Yes. You should probably specify `developmentDependency="true"` in this file: https://github.com/kfrancis/chargify-dot-net/blob/master/Source/Chargify.NET/packages.config

**Comment by TimS-** [comment]
Found this too - it seems it was added as part of this PR https://github.com/kfrancis/chargify-dot-net/pull/15

**Comment by kfrancis** [comment]
I've never known this to be an issue, or that it should only be used for development. It's not even really necessary. I can make that change.

**Comment by kfrancis** [comment]
Removed the dependency in 1.1.5935.32008
