### ISSUE TITLE
Add ability to remove a coupon from a subscription

### ISSUE THREAD

**Issue by hewittj** [kfrancis/chargify-dot-net#37]
Hey @kfrancis I mentioned this to you via Twitter but thought I would also jump in here and have a go at adding the option myself as my first time working with GitHub. Please let me know if I do anything wrong or don't follow the correct GitHub conventions though :smile: 

https://docs.chargify.com/api-coupons#api-subscription-coupon-remove

**Comment by kfrancis** [comment]
Just needed to add it to the interface, and write the test for it - thanks for the code :)

**Comment by kfrancis** [comment]
(Released in v1.1.6085.28097)
