### ISSUE TITLE
One-time charge doesn't have 'taxable' option

### ISSUE THREAD

**Issue by mysticp256** [kfrancis/chargify-dot-net#40]
Hi, when doing a one-time charge, there isn't a setting for taxable.  I have done the change in the source code but I am unable to upload it.  If you would like it, please tell me what I need to do to get it to you.

Thanks.

**Comment by kfrancis** [comment]
Hmm, I don't see `taxable` as an input option when creating a charge [see reference](https://reference.chargify.com/v1/charges/create-a-charge-2). Let me know what the source change is here if you can.

**Comment by kfrancis** [comment]
Oh, I see it now - it's not on the new documentation, it's on the [old](https://docs.chargify.com/api-charges)

**Comment by kfrancis** [comment]
It does now.
