### ISSUE TITLE
On 'GetTransactionsForSubscriptions' when supplying a sincedate and untildate, they aren't included in the query.

### ISSUE THREAD

**Issue by mysticp256** [kfrancis/chargify-dot-net#41]
On this one, you are passing the MinValue on both items which causes it to not use them. I have fixed this issue as well, I can upload my changes if you let me.

Thanks...  Here is the new source code

**Comment by kfrancis** [comment]
Let me know if you do have the source change for this, I'd like to roll this in.

**Comment by kfrancis** [comment]
If you've specified a since and until date - then it wouldn't be set to the min value .. you'll have to show me as I don't see anything wrong here.
