### ISSUE TITLE
GetMetadataFor returning list with empty strings

### ISSUE THREAD

**Issue by rdugre** [kfrancis/chargify-dot-net#42]
I have a subscription for a test site that has 3 custom fields with names and values assigned.

Below is a screenshot showing the custom fields populated for the subscription.

![2016-09-08_17-21-08](https://cloud.githubusercontent.com/assets/882287/18367411/f288bc7c-75e8-11e6-99cc-109d1ada6833.png)

When I call the GetMetadataFor like:

```
var sub = chargify.LoadSubscription(subId);
var meta = chargify.GetMetadataFor<Subscription>(subId, null);
```

I do get a MetadataResult object back with 3 items in the Metadata list, but all them have empty strings in the name and value properties. The ResourceID is also just 0 (zero).

Any ideas why this is happening?

**Comment by rdugre** [comment]
Upon further investigation, it looks like this is only happening when the "UseJson" property is set to "true" on the ChargifyConnect object. It seems the call to
```
ConvertResponseTo<MetadataResult>("metadata");
```

is constructing the object, but not placing the keys or values into the "metadata" list.

Hope that helps.

**Comment by kfrancis** [comment]
Looking into this now. Sorry for the delay, I'm back on the ball now that it's .NET Standard based :)

**Comment by kfrancis** [comment]
I see the same result, right number of objects but no content:

`{"TotalCount":3,"CurrentPage":1,"TotalPages":1,"PerPage":20,"Metadata":[{"ResourceID":0,"Value":"","Name":""},{"ResourceID":0,"Value":"","Name":""},{"ResourceID":0,"Value":"","Name":""}]}`
