### ISSUE TITLE
Invoice Payment

### ISSUE THREAD

**Issue by stfauske** [kfrancis/chargify-dot-net#43]
There seems to only be support for getting a list of invoices, while there is no support for adding a payment to an invoice, like described in the Chargify API: https://docs.chargify.com/api-invoices-payments

By just using AddPayment, the payment will not be linked to the invoice and the status will remain Unpaid.

Am I right here, or am I missing something here?

**Comment by kfrancis** [comment]
You are likely correct, a they change the API over time - I'll get that added when I get time (or you can do a PR)
