### ISSUE TITLE
entity/POCO objects to XML?

### ISSUE THREAD

**Issue by wtheronjones** [kfrancis/chargify-dot-net#44]
Thanks for putting this project out there. It is making my life much easier right now!

I have an enhancement request.

The chargify REST API will return XML, which is serialized into C# objects, I would like to be able to serialize those objects back to XML that matches the XML returned by the REST API as we'll be storing a copy of this XML in our own system.

Any plans to enhance Chargify.NET to serialize various entity type classes (ProductFamily, Product, Component, Customer, and Subscription) to their XML representation?

Even if there's no plans, I can create this XML myself, but some of the objects do not support all of the properties available in the XML.
I'll post a separate issue for those.

**Comment by kfrancis** [comment]
You can actually already obtain this, look at hooking into LogResponse or pulling the data from LastResponse. Let me know if that will work for you.
