### ISSUE TITLE
Add support for missing fields in Chargify.NET

### ISSUE THREAD

**Issue by wtheronjones** [kfrancis/chargify-dot-net#45]
I am working on converting the C# object returned from Chargify.NET back into XML, however, I'm noticing some elements in the XML returned by Charfigy's REST API are not represented as properties in the C# objects.

Example:
  Class: Product
  Missing: taxable
                initial_charge_after_trial
                update_return_params

  Class: Component:
       Supports only 3 properties(id, quantity, memo) , everything else is missing, such as: pricing_scheme, unit_name, unit_price, kind, etc.

  Class: Customer/CustomerAttributes
   Missing:
         portal_customer_created_at
         portal_invite_last_sent_at
         portal_invite_last_accepted_at

I didn't look @ the Subscription class.

I suspect that they've added new properties over time, and/ore these are non-critical type fields for the most part.

**Comment by kfrancis** [comment]
For sure, I'll get those added. They do add fields all the time, so they get added to the library when I get feedback.

**Comment by wtheronjones** [comment]
Sounds good!

**Comment by denisivin** [comment]
Would be also nice to have "current_billing_amount_in_cents" from the subscription object. Thanks.

**Comment by kfrancis** [comment]
I believe this is updated with the latest release.
