### ISSUE TITLE
PreviewRenewal method does not work

### ISSUE THREAD

**Issue by valentinas15** [kfrancis/chargify-dot-net#46]
Calling PreviewRenewal results in 	

Unexpected character encountered while parsing value: C. Path '', line 0, position 0. 
That's what we get when calling wrapper method - it looks like data structure has changed since wrapper lib was implemented.

**Comment by kfrancis** [comment]
I'll check.

**Comment by kfrancis** [comment]
Seems fine, my [test](https://github.com/kfrancis/chargify-dot-net/blob/master/Source/ChargifyDotNet.Tests/RenewalPreviewTests.cs#L13) runs successfully. Are you still having this issue?
