### ISSUE TITLE
Price Points?

### ISSUE THREAD

**Issue by MartyIce** [kfrancis/chargify-dot-net#52]
Are Price Points updatable with the API?  I searched code for "price_point_id" and "PricePoint", but didn't get any hits.

If not, are there any plans to add in near future?

Thanks!

**Comment by kfrancis** [comment]
Can add this for you if you need.

**Comment by praveen-prakash** [comment]
Yes Please do. :) I also have to implement the same in my app.

**Comment by vgooz** [comment]
When are you planing to add price points support?
I need this feature too. Thanks.

**Comment by kfrancis** [comment]
Happy to take PRs here

**Comment by asfmadx** [comment]
Is this going to be implemented?

**Comment by EdLichtman** [comment]
Haven't worked in here in a while and I definitely don't have a dev environment set up or dev credentials.

I'd be interested in trying to help, but I'd like to take some time to figure out automated tests.

**Comment by EdLichtman** [comment]
Honestly @kfrancis I don't think I'll get it done. Things have been packed. If in a week from now you still haven't gotten it done, I'll see about trying it out, but I won't start working on it unless I come back and tell you I'm doing it. I don't want to stop you from delivering value to the people who rely on your library.

**Comment by kfrancis** [comment]
Well, I remember now why I didn't add it immediately. Kind of annoying to implement, especially if I want to keep XML format alive in there as well. Working on it.

**Comment by kfrancis** [comment]
#89

**Comment by kfrancis** [comment]
See release v1.4.0.

Now, not all methods are currently implemented. I've found that this set of endpoints is rather fickle between json and XML. I'm still working on getting more information from Chargify, at which time I'll release an update.
