### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by MartyIce** [kfrancis/chargify-dot-net#53]
I was going to look into implementing price points, but am not able to compile the solution (VS 2017).  Wondering where I'm being dumb and missing something simple?  Here's a screenshot of the error dump:

![image](https://user-images.githubusercontent.com/5083039/29195776-dc53091a-7df5-11e7-9c3b-97aec7b1e34f.png)

**Comment by kfrancis** [comment]
As this is now a .NET standard library, you might need VS2017 Preview to build the solution.

**Comment by kfrancis** [comment]
You should now be able to build using non-preview, since .NET Core 2 was released along with the tooling.
