### ISSUE TITLE
Provide a usage licence.

### ISSUE THREAD

**Issue by darcythomas** [kfrancis/chargify-dot-net#6]
So that my client can have certainty that they are not going to have to open source their code base, because they used an AGPL licence library. Can you please provide a licence, that this project can be used under. 

Both here and on the nuget page.

**Comment by kfrancis** [comment]
Sorry about that, it looks like it didn't get carried over from when I moved the project from Codeplex to GitHub (which was largely manual, and not the nice automatic method).

Now that the license has been added (it's always been in the source code), I'll change the nuget release to point to the new license.

**Comment by kfrancis** [comment]
Release 1.1.5595.41432 has what you are looking for Darcy
