### ISSUE TITLE
Feature Request - Purge

### ISSUE THREAD

**Issue by ClueControl** [kfrancis/chargify-dot-net#63]
Hi,

Can the purge function be implemented to remove subscriptions?

Using a POST request: 

https://SUBDOMAIN_HERE.chargify.com/subscriptions/SUBSCRIPTION_ID_HERE/purge.json?ack=CUSTOMER_ID_HERE

**Comment by ClueControl** [comment]
I tried my hand at creating adding the purge command.  Does this look about right?  I can't compile even before any changes so still working on that. 

`/// <summary>
        /// Purge the specified subscription
        /// ** CAUTION:  Permanently deletes subscription and all revenue, no way to undo this! **
        /// </summary>
        /// https://SUBDOMAIN_HERE.chargify.com/subscriptions/SUBSCRIPTION_ID_HERE/purge.json?ack=CUSTOMER_ID_HERE
        /// <param name="SubID">The integer identifier of the subscription</param>
        /// <param name="CustID">The integer identifier of the customer for that subscription</param>
        /// <returns>True if the subscription was purged, false otherwise.</returns>
        public bool PurgeSubscription(int SubID, int CustID)
        {
            try
            {
                // make sure data is valid
                if (SubID < 0) throw new ArgumentNullException("SubID");
                if (CustID < 0) throw new ArgumentNullException("CustID");

                // now make the request
                DoRequest(string.Format("customers/{0}/purge.json?ack={1}", SubID, CustID), HttpRequestMethod.Post, string.Empty); 

                //DoRequest(string.Format("customers/{0}.{1}", chargifyId, GetMethodExtension()), HttpRequestMethod.Delete, string.Empty);
                return true;
            }
            catch (ChargifyException cex)
            {
                switch (cex.StatusCode)
                {
                    case HttpStatusCode.Forbidden:
                    case HttpStatusCode.NotFound:
                        return false;
                    default:
                        throw;
                }
            }
        }`

**Comment by ClueControl** [comment]
I tried my hand at creating a purge function.  I couldn't compile even before making changes so I am still working on that part.  Any input on how this looks would be greatly appreciated.


    /// <summary>
    /// Purge the specified subscription
        /// ** CAUTION:  Permenantly deletes subscription and all revenew, no way to undo this! **
        /// </summary>'
        /// https://SUBDOMAIN_HERE.chargify.com/subscriptions/SUBSCRIPTION_ID_HERE/purge.json?ack=CUSTOMER_ID_HERE
        /// <param name="SubID">The integer identifier of the subscription</param>
        /// <param name="CustID">The integer identifier of the customer for that subscription</param>
        /// <returns>True if the subscription was purged, false otherwise.</returns>
        public bool PurgeSubscription(int SubID, int CustID)'
        {
            try
            {
                // make sure data is valid
                if (SubID < 0) throw new ArgumentNullException("SubID");
                if (CustID < 0) throw new ArgumentNullException("CustID");

                // now make the request
                DoRequest(string.Format("customers/{0}/purge.json?ack={1}", SubID, CustID), HttpRequestMethod.Post, string.Empty); 

                return true;
            }
            catch (ChargifyException cex)
            {
                switch (cex.StatusCode)
                {
                    case HttpStatusCode.Forbidden:
                    case HttpStatusCode.NotFound:
                        return false;
                    default:
                        throw;
                }
            }
        }`
```

**Comment by kfrancis** [comment]
I can't find purge in the [documentation](https://reference.chargify.com), did they change it since you've posted?

**Comment by ClueControl** [comment]
Hi Kori!

 

Thanks for looking at this, I really appreciate it.  

 

Chargify gave me the info on 4/23.  I don’t think its changed, I just don’t think its documented.  I attached the email thread here to make sure I didn’t leave anything out.

 

Shawn

**Comment by kfrancis** [comment]
Ok, perfect! That's what I needed.

**Comment by ClueControl** [comment]
Hi Kori,

 

I know you do this as a courtesy and spare time kind of thing.  Is there anything I can do from my side to help?  I am happy to test or code review or anything like that.  Especially over this holiday – I am off work now till the 2nd and have no big plans so will be working on my own code.

 

Merry Christmas!

Shawn

**Comment by EdLichtman** [comment]
@ClueControl @kfrancis perhaps we should include in the documentation that this endpoint feature needs to be turned on by Chargify, and if they need it on, contact them at...? I created my own purge-enabled chargify connect but when I saw this feature I tried to use it but had to reach out to chargify to find out why it wasn't working.

**Comment by EdLichtman** [comment]
@kfrancis this one I also did on my mac so I didn't have intellisense -- I think I got all of the fields right -- let me know if it passes when you have the time.

Cheers,
Eddie

**Comment by EdLichtman** [comment]
https://github.com/kfrancis/chargify-dot-net/pull/73

**Comment by kfrancis** [comment]
Included in https://github.com/kfrancis/chargify-dot-net/releases/tag/v1.3.3
