### ISSUE TITLE
Add method for enabling billing portal

### ISSUE THREAD

**Issue by jpodpro** [kfrancis/chargify-dot-net#67]
We have need for programatically enabling the billing portal. Chargify supports this (https://reference.chargify.com/v1/billing-portal/enabling-billing-portal-for-customer) but there is no method for this in your API.

It doesn't look that difficult to contribute this myself. If you are unable or unwilling to do it I can try to find the time.

**Comment by EdLichtman** [comment]
@kfrancis https://github.com/kfrancis/chargify-dot-net/pull/74

Also, I expect that at least one but at most 5 tests won't pass. Could you please let me know what the Error "GetBillingManagementLink" throws says when a user doesn't have access? 

In addition, let me know if the revocation of billing portal link comes before or after enabling upon customer creation once you find out via the tests.

Cheers,
Eddie

**Comment by kfrancis** [comment]
Included in https://github.com/kfrancis/chargify-dot-net/releases/tag/v1.3.3
