### ISSUE TITLE
CreateSubscription name on credit card

### ISSUE THREAD

**Issue by davidmono** [kfrancis/chargify-dot-net#7]
Hi,

This function is ignoring name from credit card. It just takes name from customer.

CreateSubscription(string ProductHandle, ICustomerAttributes CustomerAttributes,                                                       ICreditCardAttributes CreditCardAttributes)

**Comment by kfrancis** [comment]
I don't see a method that matches that, can you point it out?

**Comment by davidmono** [comment]
Chargify.NET\ChargifyConnect.cs
Line 1792

Problem is in function on line 2564, name is not set in credit_card_attribute.

https://docs.chargify.com/api-subscriptions

> * first_name (Optional) First name on card or bank account. If omitted, the first_name from customer attributes will be used.
> * last_name (Optional) Last name on card or bank account. If omitted, the last_name from customer attributes will be used.

**Comment by kfrancis** [comment]
@davidmono Released in `1.1.5898.20266`
