### ISSUE TITLE
BUG: No ability to retrieve all subscriptions of a Specific State

### ISSUE THREAD

**Issue by EdLichtman** [kfrancis/chargify-dot-net#71]
There seems to be no ability to get more than 20 total subscriptions of a specific state. As there is paging on subscriptions without specifying state, there should be paging for subscriptions with state. 

Coincidentally, would it be useful to open another ticket to be able to gather more than 50,000 total subscriptions? because it seems GetSubscriptionList has a max of 50k (50 per page * 1000 pages)

**Comment by EdLichtman** [comment]
@kfrancis Hey man, I saw the opportunity to fix this so I've created a pull request -- I did it on my mac, and I'm not entirely certain of your testing infrastructure, so I haven't yet had the opportunity to verify that these changes are idempotent. I'd love to talk with you further about helping this project -- I don't use Twitter often, but you could find me at @EdTheDiglett and from there we could PM and discuss how I could help further via Email?

Pull Request is here:
https://github.com/kfrancis/chargify-dot-net/pull/72

**Comment by kfrancis** [comment]
Done, looks good @EdLichtman. I'll release it to nuget shortly.
