### ISSUE TITLE
BUG FIX: Update Delayed Cancelis not working

### ISSUE THREAD

**Issue by EdLichtman** [kfrancis/chargify-dot-net#75]
Hey Kori,

Not sure sure if the documentation has changed, but Update Delayed Cancel is not working -- there seems to be two endpoints, CancelDelayedCancel and UndoCancellation. 

I'm working on a bug fix and hope this will be merged in and added soon -- I'll post as soon as pull request is up.

**Comment by EdLichtman** [comment]
https://github.com/kfrancis/chargify-dot-net/pull/76

@kfrancis I did this from my Windows this time but I don't have the tests pass -- awaiting discussion over gitter to figure out how to start testing. Please let me know if tests pass

**Comment by EdLichtman** [comment]
Also @kfrancis I introduced some functional methods for code cleanup. I'm really excited to be using them if you like them, but I also don't want to introduce complexity for others trying to join the project. Please let me know if you would like me to rewrite them before pulling in the branch, and also please let me know if you would like me to start rewriting other methods to use these Functions

Cheers, 
Eddie

**Comment by kfrancis** [comment]
Included in https://github.com/kfrancis/chargify-dot-net/releases/tag/v1.3.3
