### ISSUE TITLE
Umlauts, Ampersands and other Non-Unicode Characters broken while creating customer

### ISSUE THREAD

**Issue by EdLichtman** [kfrancis/chargify-dot-net#81]
We have customers with Umlauts in their names, or other customers with & --as in "Batman & Robin" because the customer shares a joint account.

CreateCustomer does not accept ampersands or Umlauts, however Chargify does. Working on Fix in Development branch. Will notify when complete.

**Comment by EdLichtman** [comment]
Code is up for review @kfrancis

**Comment by kfrancis** [comment]
I'll check that out, thanks @EdLichtman

**Comment by EdLichtman** [comment]
@kfrancis any movement on this?

**Comment by kfrancis** [comment]
MErged
