### ISSUE TITLE
Coupon Percentage defaulting to Zero.

### ISSUE THREAD

**Issue by Glen5641** [kfrancis/chargify-dot-net#88]
I see the coupon percentage is always defaulting to zero coming from the library even with known percentages in Chargify. It may be as simple as the coupon percentage coming from Chargify's API is a floating point number in the form of a string and is being converted to an integer instead of being converted to a decimal and then cast to an integer. 

If this is still maintained, could I have help fixing this issue?

**Comment by kfrancis** [comment]
Sure, let me take a look.

**Comment by kfrancis** [comment]
And of course, feel free to fix it and send a PR.

**Comment by Glen5641** [comment]
I appreciate the message back Kori. This is an educated guess and I want to make sure this is right before I pull request. Chargify is quite new to me so I do not know the back story. I feel Chargify coupon percentage was originally an integer, but changed their API's coupon percentage to a decimal from integer in the recent past. 

A simple _percentage = (int)obj.GetJSONContentAsDecimal(key); 
On line 170 in Coupon.cs should patch the problem if programs are using this and have not noticed the bug yet.

To expand on the fix instead of patching it, I can go through and physically change the percentage to a decimal to reflect what Chargify is now.

**Comment by kfrancis** [comment]
Ah, yes - ok. I'm on it.
